name: atmos_logger
version: 0.17.0
description: "Logger package to log some messages by Atom735"
repository: https://github.com/Atom735/atmos_logger
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  io: ^1.0.3
  meta: ^1.7.0

dev_dependencies:
  atmos_lints: ^0.16.1
